# Generated by Django 2.2.6 on 2019-10-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learn_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('DS', 'Data Structres'), ('ALGOS', 'Algorithms'), ('ALGOS_ADV', 'Advanced Algorithms'), ('DS_ADV', 'Advanced Data Structures'), ('OTHER', 'Other'), ('NONE', 'NONE')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Practice_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('DS', 'Data Structres'), ('ALGOS', 'Algorithms'), ('ALGOS_ADV', 'Advanced Algorithms'), ('DS_ADV', 'Advanced Data Structures'), ('OTHER', 'Other')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Practice_Category_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Practice_Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Learn_Category_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Learn_Categories')),
            ],
        ),
    ]
