# Generated by Django 2.2.6 on 2019-10-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='!--Blank Section Title--!', max_length=120)),
                ('secText', models.TextField(blank=True, default='!--Blank Section Text--!')),
                ('hasSubSections', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('articleID', models.AutoField(primary_key=True, serialize=False)),
                ('postDate', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, default='!--Blank Article Category--!', max_length=120)),
                ('title', models.CharField(blank=True, default='!--Blank Article Title--!', max_length=120)),
                ('imagesPath', models.FilePathField(blank=True, path='static/images/article<django.db.models.fields.AutoField>', recursive=True)),
                ('preamble', models.TextField(blank=True, default='!--Blank Article Preamble--!')),
                ('time_worst', models.CharField(default=' ', max_length=1)),
                ('time_average', models.CharField(default=' ', max_length=1)),
                ('time_best', models.CharField(default=' ', max_length=1)),
                ('space_worst', models.CharField(default=' ', max_length=1)),
                ('space_average', models.CharField(default=' ', max_length=1)),
                ('space_best', models.CharField(default=' ', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('subSectionId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='!--Blank Sub Section Title--!', max_length=120)),
                ('subSecText', models.TextField(blank=True, default='!--Blank Sub Section Text--!')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subSec', to='article.Section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='article.Topic'),
        ),
        migrations.CreateModel(
            name='NotGoodFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(blank=True, default=' ', max_length=120)),
                ('item2', models.CharField(blank=True, default=' ', max_length=120)),
                ('item3', models.CharField(blank=True, default=' ', max_length=120)),
                ('item4', models.CharField(blank=True, default=' ', max_length=120)),
                ('item5', models.CharField(blank=True, default=' ', max_length=120)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notGoodFor', to='article.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='GoodFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(blank=True, default=' ', max_length=120)),
                ('item2', models.CharField(blank=True, default=' ', max_length=120)),
                ('item3', models.CharField(blank=True, default=' ', max_length=120)),
                ('item4', models.CharField(blank=True, default=' ', max_length=120)),
                ('item5', models.CharField(blank=True, default=' ', max_length=120)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodFor', to='article.Topic')),
            ],
        ),
    ]
