# Generated by Django 2.2.6 on 2019-10-12 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleID', models.AutoField(primary_key=True, serialize=False)),
                ('postDate', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, default='!--Blank Article Category--!', max_length=120)),
                ('title', models.CharField(blank=True, default='!--Blank Article Title--!', max_length=120)),
                ('imagesPath', models.FilePathField(blank=True, path='static/images/article<django.db.models.fields.AutoField>', recursive=True)),
                ('preamble', models.TextField(blank=True, default='!--Blank Article Preamble--!')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='!--Blank Section Title--!', max_length=120)),
                ('secText', models.TextField(blank=True, default='!--Blank Section Text--!')),
                ('hasSubSections', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='article.Article')),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('sectionId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='!--Blank Sub Section Title--!', max_length=120)),
                ('subSecText', models.TextField(blank=True, default='!--Blank Sub Section Text--!')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subSec', to='article.Section')),
            ],
        ),
    ]
