# Generated by Django 2.2.6 on 2019-11-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcescitations',
            name='source_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resourcescitations',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
